#!/bin/sh

@LIBEXECDIR@/alert-certificate-check >/dev/null 2>&1

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t alert-certificate-check "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
